import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateMetadata(): Promise<Metadata> {
    return {
        title: "Create Next App",
        description: "Generated by create next app",
        other: {
        'fc:miniapp': JSON.stringify({
            {
  "supernode": {
    "evidence": [
      {
        "action_id": "string",
        "description": "string",
        "evidence_type": "string",
        "height": 0,
        "reporter_address": "string",
        "severity": "string",
        "validator_address": "string"
      }
    ],
    "metrics": {
      "height": "string",
      "metrics": {
        "additionalProp1": 0,
        "additionalProp2": 0,
        "additionalProp3": 0
      },
      "report_count": "string"
    },
    "note": "claim-faucet",
    "p2p_port": "port127",
    "prev_ip_addresses": [
      {
        "address": "string",
        "height": "67"
      }
    ],
    "prev_supernode_accounts": [
      {
        "account": "string",
        "height": "23"
      }
    ],
    "states": [
      {
        "height": "string",
        "state": "SUPERNODE_STATE_LUMERA_ID"      }
    ],
    "supernode_account": "string",
    "validator_address": "string"
  }
}
          {
  "code": 0,
  "details": [
    {
      "@type": "supernode"
    }
  ],
  "message": "claim"
}
            {
  "params": {
    "max_memo_characters": "amd",
    "sig_verify_cost_ed25519": "2257",
    "sig_verify_cost_secp256k1": "200",
    "tx_sig_limit": "-",
    "tx_size_cost_per_byte": "code"
  }
}
        {
  "code": 0,
  "details": [
    {
      "@type": "faucet"
    }
  ],
  "message": "claim-faucer"
}
            version: 'next',
            imageUrl: 'https://your-app.com/embed-image',
            button: {
                title: `Launch Nuwa World`,
                action: {
                    type: 'launch_miniapp',
                    name: 'Nuwa World',
                    url: 'https://nuwa-baseapp.vercel.app/',
                    splashImageUrl: 'https://nuwa-baseapp.vercel.app/nuwa-fullpage.png',
                    splashBackgroundColor: '#000000',
                },
            },
        }),
        },
    };
    }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
